#!/bin/bash
# CAGE Framework - Multi-Node Cluster Deployment Script
# Supports: local (Docker), Kubernetes, GCP (Terraform)
#
# PROVISIONING (2026-08-02 charter): the GCP campaign path now provisions via
# terraform/ at the repo root (sessions/*.tfvars; `terraform apply` is GATED by
# explicit user approval — see terraform/main.tf header). The `gcp` command here
# drives that same root stack interactively and fail-closed (confirm prompt);
# never wire it into automation. `local`/`k8s` remain the SSH-config +
# neocloud-manual side paths.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=scripts/lib/_common.sh
source "$PROJECT_ROOT/scripts/lib/_common.sh"

# Root terraform stack (the old terraform/gcp/ subdir is GONE; sessions tfvars select the shape).
TF_DIR="$PROJECT_ROOT/terraform"

usage() {
    cat << EOF
CAGE Multi-Node Deployment Script

Usage: $0 <command> [options]

Commands:
  local           Deploy locally with Docker Compose
  k8s             Deploy to Kubernetes cluster
  gcp             Deploy to GCP with Terraform (terraform/ root stack; apply is confirm-gated)
  status          Check deployment status
  destroy [tgt]   Tear down deployment (tgt: local|k8s|gcp|all, default all)

Options:
  --replicas N    Number of vLLM replicas (default: 3)
  --model NAME    Model to serve (default: Qwen/Qwen3-4B)
  --gpu           Enable GPU support (local/k8s)
  --dry-run       Show what would be done without executing

Examples:
  $0 local --replicas 3
  $0 k8s --replicas 3 --gpu
  $0 gcp --replicas 3 --model Qwen/Qwen3-8B
  $0 status
  $0 destroy local

EOF
}

log_info()  { printf '[INFO] %s\n' "$1"; }
log_warn()  { printf '[WARN] %s\n' "$1" >&2; }
log_error() { printf '[ERROR] %s\n' "$1" >&2; }

# Default values
REPLICAS=3
MODEL="Qwen/Qwen3-4B"
GPU_ENABLED=false
DRY_RUN=false
COMMAND=""
TARGET=""

# Parse arguments. The FIRST bare word is the command; a SECOND bare word is the
# target (so `destroy local` works — previously the second word overwrote COMMAND
# and `destroy local` silently ran a local DEPLOY).
while [[ $# -gt 0 ]]; do
    case "$1" in
        local|k8s|gcp|status|destroy)
            if [[ -z "$COMMAND" ]]; then
                COMMAND="$1"
            elif [[ -z "$TARGET" ]]; then
                TARGET="$1"
            else
                log_error "unexpected extra argument: $1"
                usage
                exit 1
            fi
            shift
            ;;
        --replicas)
            REPLICAS="${2:?--replicas needs a value}"
            shift 2
            ;;
        --model)
            MODEL="${2:?--model needs a value}"
            shift 2
            ;;
        --gpu)
            GPU_ENABLED=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

if [[ -z "$COMMAND" ]]; then
    usage
    exit 1
fi

# Generate docker-compose for local deployment
generate_docker_compose() {
    local compose_file="$PROJECT_ROOT/docker-compose.generated.yml"

    cat > "$compose_file" << EOF
# Auto-generated by deploy_cluster.sh
# DO NOT EDIT - regenerate with: ./scripts/2_serving/deploy_cluster.sh local

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

EOF

    # Add vLLM replicas
    local i port
    for i in $(seq 1 "$REPLICAS"); do
        port=$((8000 + i))
        cat >> "$compose_file" << EOF
  vllm-replica-$i:
    image: vllm/vllm-openai:v0.19.1
EOF
        if "$GPU_ENABLED"; then
            cat >> "$compose_file" << EOF
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
EOF
        fi
        cat >> "$compose_file" << EOF
    command: ["--model", "$MODEL", "--port", "$port", "--enable-prefix-caching", "--enable-prompt-tokens-details"]
    ports:
      - "$port:$port"
    environment:
      - VLLM_CPU_KVCACHE_SPACE=10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$port/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

EOF
    done

    # Add router
    local replica_env="replica-1=http://vllm-replica-1:8001"
    for i in $(seq 2 "$REPLICAS"); do
        port=$((8000 + i))
        replica_env="$replica_env,replica-$i=http://vllm-replica-$i:$port"
    done

    cat >> "$compose_file" << EOF
  cage-router:
    build:
      context: .
      dockerfile: docker/Dockerfile.router
    ports:
      - "9000:9000"
    environment:
      - ROUTER_REPLICAS=$replica_env
    depends_on:
EOF
    for i in $(seq 1 "$REPLICAS"); do
        echo "      - vllm-replica-$i" >> "$compose_file"
    done

    echo "$compose_file"
}

# Deploy locally with Docker Compose
deploy_local() {
    log_info "Deploying CAGE cluster locally with $REPLICAS replicas..."

    require_cmd docker "install Docker first"

    local compose_file
    compose_file=$(generate_docker_compose)
    log_info "Generated docker-compose file: $compose_file"

    if "$DRY_RUN"; then
        log_info "[DRY RUN] Would run: docker compose -f $compose_file up -d"
        cat "$compose_file"
        return
    fi

    # Create router Dockerfile if it doesn't exist
    mkdir -p "$PROJECT_ROOT/docker"
    if [[ ! -f "$PROJECT_ROOT/docker/Dockerfile.router" ]]; then
        cat > "$PROJECT_ROOT/docker/Dockerfile.router" << 'EOF'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ src/
EXPOSE 9000
CMD ["python", "-m", "src.orchestration.router"]
EOF
    fi

    # Start services
    cd "$PROJECT_ROOT"
    docker compose -f "$compose_file" up -d

    log_info "Waiting for services to start..."
    sleep 10

    # Check health
    check_local_status
}

# Deploy to Kubernetes
deploy_k8s() {
    log_info "Deploying CAGE cluster to Kubernetes with $REPLICAS replicas..."

    require_cmd kubectl "install kubectl first"

    # Check cluster connection
    if ! kubectl cluster-info > /dev/null 2>&1; then
        log_error "Cannot connect to Kubernetes cluster. Check your kubeconfig."
        exit 1
    fi

    # Fail loud: the manifests directory must exist (a missing k8s/ used to make
    # `kubectl apply` fail one file at a time under set -e with no explanation).
    if [[ ! -d "$PROJECT_ROOT/k8s" ]]; then
        log_error "k8s/ manifest directory not found at $PROJECT_ROOT/k8s -- nothing to apply."
        exit 1
    fi

    if "$DRY_RUN"; then
        log_info "[DRY RUN] Would apply K8s manifests from k8s/"
        return
    fi

    cd "$PROJECT_ROOT/k8s"

    # Apply manifests
    kubectl apply -f redis.yaml
    kubectl apply -f vllm-replica.yaml
    kubectl apply -f router.yaml

    log_info "Waiting for pods to be ready..."
    kubectl wait --for=condition=ready pod -l app=cage-redis --timeout=60s
    kubectl wait --for=condition=ready pod -l app=vllm-replica-1 --timeout=300s || true

    # Get router NodePort
    local nodeport
    nodeport=$(kubectl get svc cage-router -o jsonpath='{.spec.ports[0].nodePort}')
    log_info "Router available at NodePort: $nodeport"
    log_info "Run experiments with: --api-base http://<node-ip>:$nodeport"
}

# Deploy to GCP with Terraform (root terraform/ stack; sessions tfvars select the shape).
deploy_gcp() {
    log_info "Deploying CAGE cluster to GCP with $REPLICAS replicas..."

    require_cmd terraform "install Terraform first"
    require_cmd gcloud "install the Google Cloud SDK first"

    cd "$TF_DIR"

    # Check for tfvars
    if [[ ! -f "terraform.tfvars" ]]; then
        log_error "terraform.tfvars not found in terraform/. Copy terraform.tfvars.example and fill in your values."
        log_error "Campaign sessions additionally use -var-file=sessions/<group>.tfvars (see terraform/main.tf)."
        exit 1
    fi

    if "$DRY_RUN"; then
        terraform plan -var="num_replicas=$REPLICAS" -var="model_name=$MODEL"
        return
    fi

    # RUN-APPROVAL GATE (standing discipline, 2026-07-16): apply starts billing.
    # confirm() is fail-closed -- with no TTY the answer is NO unless CAGE_ASSUME_YES=1.
    terraform init
    terraform plan -var="num_replicas=$REPLICAS" -var="model_name=$MODEL"
    if ! confirm "terraform APPLY the plan above (BILLING STARTS)?"; then
        log_warn "apply NOT confirmed -- nothing created, still \$0."
        exit 1
    fi
    terraform apply -var="num_replicas=$REPLICAS" -var="model_name=$MODEL" -auto-approve

    # Show outputs
    log_info "Deployment complete!"
    terraform output
}

# Check deployment status
check_status() {
    log_info "Checking deployment status..."

    # Check local Docker
    if [[ -f "$PROJECT_ROOT/docker-compose.generated.yml" ]] \
        && docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" ps > /dev/null 2>&1; then
        log_info "Local Docker deployment:"
        docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" ps
    fi

    # Check Kubernetes
    if command -v kubectl > /dev/null 2>&1 && kubectl get pods -l app=cage-router > /dev/null 2>&1; then
        log_info "Kubernetes deployment:"
        kubectl get pods -l app=cage-router -l app=vllm-replica-1 -l app=cage-redis
    fi

    # Check GCP Terraform (root stack)
    if [[ -f "$TF_DIR/terraform.tfstate" ]]; then
        log_info "GCP deployment:"
        cd "$TF_DIR"
        terraform output 2>/dev/null || true
    fi
}

check_local_status() {
    log_info "Checking local services..."

    # Check Redis
    if curl -s http://localhost:6379 > /dev/null 2>&1 || redis-cli ping > /dev/null 2>&1; then
        log_info "OK Redis is running"
    else
        log_warn "XX Redis not responding"
    fi

    # Check vLLM replicas (-f: an HTTP 5xx must read as UNHEALTHY, not as exit 0)
    local i port
    for i in $(seq 1 "$REPLICAS"); do
        port=$((8000 + i))
        if curl -fs "http://localhost:$port/health" > /dev/null 2>&1; then
            log_info "OK vLLM replica $i is healthy (port $port)"
        else
            log_warn "XX vLLM replica $i not responding (port $port)"
        fi
    done

    # Check router
    if curl -fs "http://localhost:9000/health" > /dev/null 2>&1; then
        log_info "OK CAGE Router is healthy"
        log_info "Run experiments with: --api-base http://localhost:9000"
    else
        log_warn "XX CAGE Router not responding"
    fi
}

# Destroy deployment. (Explicit if-blocks, not `;;&` fallthrough: `;;&` is bash-4-only
# and choked `bash -n` on macOS bash 3.2.)
destroy_deployment() {
    local target="${1:-all}"

    log_info "Destroying deployment: $target"

    if "$DRY_RUN"; then
        log_info "[DRY RUN] Would destroy $target deployment"
        return
    fi

    if [[ "$target" == "local" || "$target" == "all" ]]; then
        if [[ -f "$PROJECT_ROOT/docker-compose.generated.yml" ]]; then
            docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" down -v
            rm -f "$PROJECT_ROOT/docker-compose.generated.yml"
            log_info "Local deployment destroyed"
        fi
    fi

    if [[ "$target" == "k8s" || "$target" == "all" ]]; then
        if command -v kubectl > /dev/null 2>&1 && [[ -d "$PROJECT_ROOT/k8s" ]] \
            && kubectl get namespace default > /dev/null 2>&1; then
            kubectl delete -f "$PROJECT_ROOT/k8s/" --ignore-not-found=true
            log_info "Kubernetes deployment destroyed"
        fi
    fi

    if [[ "$target" == "gcp" || "$target" == "all" ]]; then
        if [[ -f "$TF_DIR/terraform.tfstate" ]]; then
            cd "$TF_DIR"
            log_info "Terraform destroy of the root stack. Data flush on destroy relies on each"
            log_info "node's shutdown-script (metadata) syncing to GCS within its shutdown window."
            log_info "For a single VM, prefer 'scripts/6_teardown/teardown_vm.sh <vm> <zone>', which"
            log_info "verifies this run's GCS log sentinel AND pulls results local BEFORE deleting"
            log_info "(fail-closed). PULL RESULTS LOCAL FIRST -- teardown is irreversible."
            # Fail-closed confirm replaces the old 'sleep 5 then destroy anyway' window.
            if ! confirm "terraform DESTROY the GCP cluster (results pulled local already)?"; then
                log_warn "destroy NOT confirmed -- GCP deployment left as-is (STILL BILLING)."
                return 1
            fi
            terraform destroy -auto-approve
            log_info "GCP deployment destroyed"
        fi
    fi
}

# Main command dispatch
case "$COMMAND" in
    local)
        deploy_local
        ;;
    k8s)
        deploy_k8s
        ;;
    gcp)
        deploy_gcp
        ;;
    status)
        check_status
        ;;
    destroy)
        destroy_deployment "${TARGET:-all}"
        ;;
    *)
        log_error "Unknown command: $COMMAND"
        usage
        exit 1
        ;;
esac
