#!/bin/bash
# CAGE Framework - Multi-Node Cluster Deployment Script
# Supports: local (Docker), Kubernetes, GCP (Terraform)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

usage() {
    cat << EOF
CAGE Multi-Node Deployment Script

Usage: $0 <command> [options]

Commands:
  local           Deploy locally with Docker Compose
  k8s             Deploy to Kubernetes cluster
  gcp             Deploy to GCP with Terraform
  status          Check deployment status
  destroy         Tear down deployment

Options:
  --replicas N    Number of vLLM replicas (default: 3)
  --model NAME    Model to serve (default: Qwen/Qwen3-4B)
  --gpu           Enable GPU support (local/k8s)
  --dry-run       Show what would be done without executing

Examples:
  $0 local --replicas 3
  $0 k8s --replicas 3 --gpu
  $0 gcp --replicas 3 --model Qwen/Qwen3-8B
  $0 status
  $0 destroy local

EOF
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Default values
REPLICAS=3
MODEL="Qwen/Qwen3-4B"
GPU_ENABLED=false
DRY_RUN=false
COMMAND=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        local|k8s|gcp|status|destroy)
            COMMAND="$1"
            shift
            ;;
        --replicas)
            REPLICAS="$2"
            shift 2
            ;;
        --model)
            MODEL="$2"
            shift 2
            ;;
        --gpu)
            GPU_ENABLED=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

if [[ -z "$COMMAND" ]]; then
    usage
    exit 1
fi

# Generate docker-compose for local deployment
generate_docker_compose() {
    local compose_file="$PROJECT_ROOT/docker-compose.generated.yml"
    
    cat > "$compose_file" << EOF
# Auto-generated by deploy_cluster.sh
# DO NOT EDIT - regenerate with: ./scripts/2_serving/deploy_cluster.sh local

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

EOF

    # Add vLLM replicas
    for i in $(seq 1 $REPLICAS); do
        local port=$((8000 + i))
        cat >> "$compose_file" << EOF
  vllm-replica-$i:
    image: vllm/vllm-openai:v0.11.0
EOF
        if $GPU_ENABLED; then
            cat >> "$compose_file" << EOF
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
EOF
        fi
        cat >> "$compose_file" << EOF
    command: ["--model", "$MODEL", "--port", "$port", "--enable-prefix-caching", "--enable-prompt-tokens-details"]
    ports:
      - "$port:$port"
    environment:
      - VLLM_CPU_KVCACHE_SPACE=10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$port/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

EOF
    done

    # Add router
    local replica_env="replica-1=http://vllm-replica-1:8001"
    for i in $(seq 2 $REPLICAS); do
        local port=$((8000 + i))
        replica_env="$replica_env,replica-$i=http://vllm-replica-$i:$port"
    done

    cat >> "$compose_file" << EOF
  cage-router:
    build:
      context: .
      dockerfile: docker/Dockerfile.router
    ports:
      - "9000:9000"
    environment:
      - ROUTER_REPLICAS=$replica_env
    depends_on:
EOF
    for i in $(seq 1 $REPLICAS); do
        echo "      - vllm-replica-$i" >> "$compose_file"
    done

    echo "$compose_file"
}

# Deploy locally with Docker Compose
deploy_local() {
    log_info "Deploying CAGE cluster locally with $REPLICAS replicas..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker not found. Please install Docker first."
        exit 1
    fi
    
    # Generate compose file
    local compose_file=$(generate_docker_compose)
    log_info "Generated docker-compose file: $compose_file"
    
    if $DRY_RUN; then
        log_info "[DRY RUN] Would run: docker compose -f $compose_file up -d"
        cat "$compose_file"
        return
    fi
    
    # Create router Dockerfile if it doesn't exist
    mkdir -p "$PROJECT_ROOT/docker"
    if [[ ! -f "$PROJECT_ROOT/docker/Dockerfile.router" ]]; then
        cat > "$PROJECT_ROOT/docker/Dockerfile.router" << 'EOF'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ src/
EXPOSE 9000
CMD ["python", "-m", "src.orchestration.router"]
EOF
    fi
    
    # Start services
    cd "$PROJECT_ROOT"
    docker compose -f "$compose_file" up -d
    
    log_info "Waiting for services to start..."
    sleep 10
    
    # Check health
    check_local_status
}

# Deploy to Kubernetes
deploy_k8s() {
    log_info "Deploying CAGE cluster to Kubernetes with $REPLICAS replicas..."
    
    # Check kubectl
    if ! command -v kubectl &> /dev/null; then
        log_error "kubectl not found. Please install kubectl first."
        exit 1
    fi
    
    # Check cluster connection
    if ! kubectl cluster-info &> /dev/null; then
        log_error "Cannot connect to Kubernetes cluster. Check your kubeconfig."
        exit 1
    fi
    
    if $DRY_RUN; then
        log_info "[DRY RUN] Would apply K8s manifests from k8s/"
        return
    fi
    
    cd "$PROJECT_ROOT/k8s"
    
    # Apply manifests
    kubectl apply -f redis.yaml
    kubectl apply -f vllm-replica.yaml
    kubectl apply -f router.yaml
    
    log_info "Waiting for pods to be ready..."
    kubectl wait --for=condition=ready pod -l app=cage-redis --timeout=60s
    kubectl wait --for=condition=ready pod -l app=vllm-replica-1 --timeout=300s || true
    
    # Get router NodePort
    local nodeport=$(kubectl get svc cage-router -o jsonpath='{.spec.ports[0].nodePort}')
    log_info "Router available at NodePort: $nodeport"
    log_info "Run experiments with: --api-base http://<node-ip>:$nodeport"
}

# Deploy to GCP with Terraform
deploy_gcp() {
    log_info "Deploying CAGE cluster to GCP with $REPLICAS replicas..."
    
    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        log_error "Terraform not found. Please install Terraform first."
        exit 1
    fi
    
    # Check gcloud
    if ! command -v gcloud &> /dev/null; then
        log_error "gcloud not found. Please install Google Cloud SDK first."
        exit 1
    fi
    
    cd "$PROJECT_ROOT/terraform/gcp"
    
    # Check for tfvars
    if [[ ! -f "terraform.tfvars" ]]; then
        log_error "terraform.tfvars not found. Copy terraform.tfvars.example and fill in your values."
        exit 1
    fi
    
    if $DRY_RUN; then
        terraform plan -var="num_replicas=$REPLICAS" -var="model_name=$MODEL"
        return
    fi
    
    # Initialize and apply
    terraform init
    terraform apply -var="num_replicas=$REPLICAS" -var="model_name=$MODEL" -auto-approve
    
    # Show outputs
    log_info "Deployment complete!"
    terraform output
}

# Check deployment status
check_status() {
    local target="${1:-all}"
    
    log_info "Checking deployment status..."
    
    # Check local Docker
    if docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" ps &> /dev/null 2>&1; then
        log_info "Local Docker deployment:"
        docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" ps
    fi
    
    # Check Kubernetes
    if kubectl get pods -l app=cage-router &> /dev/null 2>&1; then
        log_info "Kubernetes deployment:"
        kubectl get pods -l app=cage-router -l app=vllm-replica-1 -l app=cage-redis
    fi
    
    # Check GCP Terraform
    if [[ -f "$PROJECT_ROOT/terraform/gcp/terraform.tfstate" ]]; then
        log_info "GCP deployment:"
        cd "$PROJECT_ROOT/terraform/gcp"
        terraform output 2>/dev/null || true
    fi
}

check_local_status() {
    log_info "Checking local services..."
    
    # Check Redis
    if curl -s http://localhost:6379 &> /dev/null || redis-cli ping &> /dev/null 2>&1; then
        log_info "✓ Redis is running"
    else
        log_warn "✗ Redis not responding"
    fi
    
    # Check vLLM replicas
    for i in $(seq 1 $REPLICAS); do
        local port=$((8000 + i))
        if curl -s "http://localhost:$port/health" &> /dev/null; then
            log_info "✓ vLLM replica $i is healthy (port $port)"
        else
            log_warn "✗ vLLM replica $i not responding (port $port)"
        fi
    done
    
    # Check router
    if curl -s "http://localhost:9000/health" &> /dev/null; then
        log_info "✓ CAGE Router is healthy"
        log_info "Run experiments with: --api-base http://localhost:9000"
    else
        log_warn "✗ CAGE Router not responding"
    fi
}

# Destroy deployment
destroy_deployment() {
    local target="${1:-all}"
    
    log_info "Destroying deployment: $target"
    
    if $DRY_RUN; then
        log_info "[DRY RUN] Would destroy $target deployment"
        return
    fi
    
    case $target in
        local|all)
            if [[ -f "$PROJECT_ROOT/docker-compose.generated.yml" ]]; then
                docker compose -f "$PROJECT_ROOT/docker-compose.generated.yml" down -v
                rm -f "$PROJECT_ROOT/docker-compose.generated.yml"
                log_info "Local deployment destroyed"
            fi
            ;;&
        k8s|all)
            if kubectl get namespace default &> /dev/null 2>&1; then
                kubectl delete -f "$PROJECT_ROOT/k8s/" --ignore-not-found=true
                log_info "Kubernetes deployment destroyed"
            fi
            ;;&
        gcp|all)
            if [[ -f "$PROJECT_ROOT/terraform/gcp/terraform.tfstate" ]]; then
                cd "$PROJECT_ROOT/terraform/gcp"
                log_info "Unconditional 'terraform destroy'. Data flush on destroy relies on each"
                log_info "node's shutdown-script (metadata) syncing to GCS within its shutdown window."
                log_info "For the single Phase-2 VM, prefer 'scripts/6_teardown/teardown_vm.sh <vm> <zone>', which"
                log_info "verifies this run's GCS log sentinel BEFORE deleting (fail-closed)."
                log_info "Destroying the cluster in 5s (Ctrl-C to abort)..."
                sleep 5
                terraform destroy -auto-approve
                log_info "GCP deployment destroyed"
            fi
            ;;
    esac
}

# Main command dispatch
case $COMMAND in
    local)
        deploy_local
        ;;
    k8s)
        deploy_k8s
        ;;
    gcp)
        deploy_gcp
        ;;
    status)
        check_status
        ;;
    destroy)
        destroy_deployment "${2:-all}"
        ;;
    *)
        log_error "Unknown command: $COMMAND"
        usage
        exit 1
        ;;
esac
