python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset squad_v2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-4B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset squad_v2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen3-8B --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset squad_v2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode single --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode batched --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline no_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline prefix_cache --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy sharded_context
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline distributed --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --api-base http://localhost:8000 --sharding-policy replicated
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline redis --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline rag --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
python3 scripts/run_experiment.py --model Qwen/Qwen2.5-7B-Instruct --dataset trivia_qa --truncate-prompt-tokens 1024 --max-context-chars 300 --max-context-docs 2 --workload-mode multi_turn --baseline hybrid --repeat-queries 2 --output-dir experiments/run/simulation-distrub-local/results --max-tokens 256 --top-k-sweep --top-k-values 1,3,5,10
